// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// runSim
NumericMatrix runSim(const int ncol, const int begin, const int end, const int year_stop, const NumericVector& smoking_params, const NumericVector& smoking_calibration_params, const NumericVector& lc_baseline_risk_params, const NumericMatrix& lc_dwell_weibull_params, const NumericMatrix& lc_transition_rates, const NumericVector& lc_survival_params, const NumericMatrix& utility, const NumericMatrix& ave_cost, const int screen, const NumericVector& strategy_cond, const int trunc_age, const int smoking_ban_policy_index, const int screen_mode, const int sensitivity_level, const bool verbose);
RcppExport SEXP _DemosMiscanLung_runSim(SEXP ncolSEXP, SEXP beginSEXP, SEXP endSEXP, SEXP year_stopSEXP, SEXP smoking_paramsSEXP, SEXP smoking_calibration_paramsSEXP, SEXP lc_baseline_risk_paramsSEXP, SEXP lc_dwell_weibull_paramsSEXP, SEXP lc_transition_ratesSEXP, SEXP lc_survival_paramsSEXP, SEXP utilitySEXP, SEXP ave_costSEXP, SEXP screenSEXP, SEXP strategy_condSEXP, SEXP trunc_ageSEXP, SEXP smoking_ban_policy_indexSEXP, SEXP screen_modeSEXP, SEXP sensitivity_levelSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< const int >::type begin(beginSEXP);
    Rcpp::traits::input_parameter< const int >::type end(endSEXP);
    Rcpp::traits::input_parameter< const int >::type year_stop(year_stopSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type smoking_params(smoking_paramsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type smoking_calibration_params(smoking_calibration_paramsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type lc_baseline_risk_params(lc_baseline_risk_paramsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type lc_dwell_weibull_params(lc_dwell_weibull_paramsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type lc_transition_rates(lc_transition_ratesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type lc_survival_params(lc_survival_paramsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type utility(utilitySEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type ave_cost(ave_costSEXP);
    Rcpp::traits::input_parameter< const int >::type screen(screenSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type strategy_cond(strategy_condSEXP);
    Rcpp::traits::input_parameter< const int >::type trunc_age(trunc_ageSEXP);
    Rcpp::traits::input_parameter< const int >::type smoking_ban_policy_index(smoking_ban_policy_indexSEXP);
    Rcpp::traits::input_parameter< const int >::type screen_mode(screen_modeSEXP);
    Rcpp::traits::input_parameter< const int >::type sensitivity_level(sensitivity_levelSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(runSim(ncol, begin, end, year_stop, smoking_params, smoking_calibration_params, lc_baseline_risk_params, lc_dwell_weibull_params, lc_transition_rates, lc_survival_params, utility, ave_cost, screen, strategy_cond, trunc_age, smoking_ban_policy_index, screen_mode, sensitivity_level, verbose));
    return rcpp_result_gen;
END_RCPP
}
// schedule_population
NumericMatrix schedule_population(const int ncol, const int begin, const int end, const int year_stop, const NumericVector& smoking_params, const NumericVector& smoking_calibration_params, const NumericVector& lc_baseline_risk_params, const NumericMatrix& lc_dwell_weibull_params, const NumericMatrix& lc_transition_rates, const NumericVector& lc_survival_params, const NumericMatrix& utility, const NumericMatrix& ave_cost, const int screen, const NumericVector& strategy_cond, const int trunc_age, const int smoking_ban_policy_index, const int screen_mode, const int sensitivity_level, const bool verbose);
RcppExport SEXP _DemosMiscanLung_schedule_population(SEXP ncolSEXP, SEXP beginSEXP, SEXP endSEXP, SEXP year_stopSEXP, SEXP smoking_paramsSEXP, SEXP smoking_calibration_paramsSEXP, SEXP lc_baseline_risk_paramsSEXP, SEXP lc_dwell_weibull_paramsSEXP, SEXP lc_transition_ratesSEXP, SEXP lc_survival_paramsSEXP, SEXP utilitySEXP, SEXP ave_costSEXP, SEXP screenSEXP, SEXP strategy_condSEXP, SEXP trunc_ageSEXP, SEXP smoking_ban_policy_indexSEXP, SEXP screen_modeSEXP, SEXP sensitivity_levelSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< const int >::type begin(beginSEXP);
    Rcpp::traits::input_parameter< const int >::type end(endSEXP);
    Rcpp::traits::input_parameter< const int >::type year_stop(year_stopSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type smoking_params(smoking_paramsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type smoking_calibration_params(smoking_calibration_paramsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type lc_baseline_risk_params(lc_baseline_risk_paramsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type lc_dwell_weibull_params(lc_dwell_weibull_paramsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type lc_transition_rates(lc_transition_ratesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type lc_survival_params(lc_survival_paramsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type utility(utilitySEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type ave_cost(ave_costSEXP);
    Rcpp::traits::input_parameter< const int >::type screen(screenSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type strategy_cond(strategy_condSEXP);
    Rcpp::traits::input_parameter< const int >::type trunc_age(trunc_ageSEXP);
    Rcpp::traits::input_parameter< const int >::type smoking_ban_policy_index(smoking_ban_policy_indexSEXP);
    Rcpp::traits::input_parameter< const int >::type screen_mode(screen_modeSEXP);
    Rcpp::traits::input_parameter< const int >::type sensitivity_level(sensitivity_levelSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(schedule_population(ncol, begin, end, year_stop, smoking_params, smoking_calibration_params, lc_baseline_risk_params, lc_dwell_weibull_params, lc_transition_rates, lc_survival_params, utility, ave_cost, screen, strategy_cond, trunc_age, smoking_ban_policy_index, screen_mode, sensitivity_level, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DemosMiscanLung_runSim", (DL_FUNC) &_DemosMiscanLung_runSim, 19},
    {"_DemosMiscanLung_schedule_population", (DL_FUNC) &_DemosMiscanLung_schedule_population, 19},
    {NULL, NULL, 0}
};

RcppExport void R_init_DemosMiscanLung(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
