# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runSim <- function(ncol, begin, end, year_stop, smoking_params, smoking_calibration_params, lc_baseline_risk_params, lc_dwell_weibull_params, lc_transition_rates, lc_survival_params, utility, ave_cost, screen, strategy_cond, trunc_age, smoking_ban_policy_index, screen_mode, sensitivity_level, verbose) {
    .Call(`_DemosMiscanLung_runSim`, ncol, begin, end, year_stop, smoking_params, smoking_calibration_params, lc_baseline_risk_params, lc_dwell_weibull_params, lc_transition_rates, lc_survival_params, utility, ave_cost, screen, strategy_cond, trunc_age, smoking_ban_policy_index, screen_mode, sensitivity_level, verbose)
}

schedule_population <- function(ncol, begin, end, year_stop, smoking_params, smoking_calibration_params, lc_baseline_risk_params, lc_dwell_weibull_params, lc_transition_rates, lc_survival_params, utility, ave_cost, screen, strategy_cond, trunc_age, smoking_ban_policy_index, screen_mode, sensitivity_level, verbose) {
    .Call(`_DemosMiscanLung_schedule_population`, ncol, begin, end, year_stop, smoking_params, smoking_calibration_params, lc_baseline_risk_params, lc_dwell_weibull_params, lc_transition_rates, lc_survival_params, utility, ave_cost, screen, strategy_cond, trunc_age, smoking_ban_policy_index, screen_mode, sensitivity_level, verbose)
}

